---
version: "2.1"
services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    user: root
    ports:
      - 1080:8080
      - 50000:50000
    volumes:
      - ./jenkins-home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    privileged: true
    restart: unless-stopped
